version: '3.8'

services:
  daemon:
    build:
      context: daemon/
      dockerfile: Dockerfile
    restart: always
    environment: &env
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MAX_MIND_API_KEY: ${MAX_MIND_API_KEY}
    ports:
      - 27500:27500/udp

  nginx:
    build:
      context: nginx/
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:80
    depends_on:
      - php

  php:
    build:
      context: php/
      dockerfile: Dockerfile
    restart: always
    environment: *env
    expose:
      - 9000

  mysql:
    image: mysql:5.7
    command: --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

volumes:
  mysql-data:

networks:
  default:
    name: hlxce-dev-network