version: '3.8'

services:
  cronjob:
    image: bogdannbv/hlxce-cronjob
    container_name: hlxce-cronjob
    restart: "no"
    environment:
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

networks:
  default:
      name: hlxce-network